# Generated by Django 5.1.6 on 2025-03-21 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0002_alter_promotion_options_promotion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
