# Generated by Django 5.1.6 on 2025-03-24 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promotions', '0003_promotion_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image_cover',
            field=models.ImageField(blank=True, null=True, upload_to='promotions'),
        ),
    ]
